#!/bin/bash

SRC_DIR="src"
TARGET_DIR="target"
ENTRY_CLASS="Allocator"
PROGRAM_NAME="allocator"

rm -f "$PROGRAM_NAME.jar"

mkdir $TARGET_DIR

echo "Compiling Java files..."
COMPILE_OUTPUT=$(javac -d $TARGET_DIR $(find $SRC_DIR -name *.java) 2>&1)

if [ $? -ne 0 ]; then
	echo "Compilation failed."
	echo $COMPILE_OUTPUT
	exit 1
fi

jar cfm "$PROGRAM_NAME.jar" manifest.txt -C target/ .

rm -rf $TARGET_DIR

echo "Compiled successfully."

